In [9]:
import numpy as np

In [10]:
# 读入数据
A = [[1,1/5,1/3],[5,1,3],[3,1/3,1]]
A = np.array(A)
A

array([[1.        , 0.2       , 0.33333333],
       [5.        , 1.        , 3.        ],
       [3.        , 0.33333333, 1.        ]])

In [11]:
# 求列和
a1 = A.sum(axis=0)
a1

array([9.        , 1.53333333, 4.33333333])

In [12]:
# 列归一化
a2 = A/a1
a2

array([[0.11111111, 0.13043478, 0.07692308],
       [0.55555556, 0.65217391, 0.69230769],
       [0.33333333, 0.2173913 , 0.23076923]])

In [13]:
# 行求和
a3 = a2.sum(axis=1)
a3

array([0.31846897, 1.90003716, 0.78149387])

In [14]:
# 归一化求权重w
w = a3/a3.sum()
w

array([0.10615632, 0.63334572, 0.26049796])

In [15]:
# 求特征根值
k = (np.dot(A,w)/w).mean()
k

3.0387146809594667

In [16]:
# 一致性检验
CI = (k-len(A))/(k-1)
CI

0.018989749434308627

In [17]:
RI = 0.52
CR = CI/RI
if CR>0.1:
    print('不满足一致性检验')
else:
    print('满足,CR=%f'%CR)

满足,CR=0.036519


In [18]:
# 求得分
c1 = np.array([0.64,0.25,0.11])
c2 = np.array([0.24,0.55,0.21])
c3 = np.array([0.34,0.25,0.41])


In [23]:
score1 = (c1*w).sum()
score2 = (c2*w).sum()
score3 = (c3*w).sum()
print('score1=%0.3f'%score1)
print('score2=%0.3f'%score2)
print('score3=%0.3f'%score3)

score1=0.255
score2=0.429
score3=0.301


In [24]:
w=np.array([0.106,0.633,0.261])

In [25]:
np.dot(A,w)

array([0.3196, 1.946 , 0.79  ])